---
- name: Generate Certificate for EOS API and avoid SSLv3 errors
  hosts: ceos

  tasks:
  - name: configure SSL certificate
    eos_command:
      commands:
        - "enable"
        - "security pki key generate rsa 2048 self-signed.key"
        - "security pki certificate generate self-signed self-signed.crt key self-signed.key validity 365 parameters common-name {{inventory_hostname.split('-')[-1]}} country US state CA locality SantaClara organization Example organization-unit IT subject-alternative-name dns {{inventory_hostname.split('-')[-1]}} subject-alternative-name ip {{hostvars[inventory_hostname].ansible_host}}"
        - "configure"
        - "management security"
        - "ssl profile selfSignedSSLProfile"
        - "certificate self-signed.crt key self-signed.key"
        - "tls versions 1.2"
        - "cipher-list AESGCM"
        - "management api http-commands"
        - "protocol https ssl profile selfSignedSSLProfile"
