---
- name: Collect Facts for testing topology
  hosts: AVD_LAB

  tasks:
  - name: Gather EOS facts
    arista.eos.eos_facts:
      gather_subset:
      - '!all'
      - '!min'
      gather_network_resources:
      - interfaces