- name: Build Switch configuration
  hosts: DC1_FABRIC
  tasks:
    - name: generate intend variables
      tags: [build]
      import_role:
        name: arista.avd.eos_designs
    - name: generate device intended config and documentation
      tags: [build]
      import_role:
        name: arista.avd.eos_cli_config_gen