---
fabric_name: DC1_FABRIC

underlay_routing_protocol: EBGP

overlay_routing_protocol: EBGP

vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="


spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
      #- update wait-for-convergence
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  nodes:
    clab-evpnlab-spine1:
      id: 1
      mgmt_ip: "{{ansible_host}}/24"
      router_id: 192.168.255.10
    clab-evpnlab-spine2:
      id: 2
      mgmt_ip: "{{ansible_host}}/24"
      router_id: 192.168.255.11



l3leaf:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65100
    # Uplink switches (list).
    uplink_switches: [clab-evpnlab-spine1,clab-evpnlab-spine2]
    # Local uplink interfaces (list).
    uplink_interfaces: [Ethernet1,Ethernet2]
    virtual_router_mac_address: 00:00:00:00:00:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_ipv4_pool: 172.31.255.0/24
    bgp_defaults:
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ Tenant_A, Tenant_B ]
        tags: [ odd_network, even_network ]
      nodes:
        clab-evpnlab-leaf1:
          id: 1
          mgmt_ip: "{{ansible_host}}/24"
          # Uplink switches interfaces (list), interface located on uplink switch. 
          uplink_switch_interfaces: [Ethernet1,Ethernet1]
          vtep_ip: 192.168.254.30
          router_id: 192.168.255.30

    DC1_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ Tenant_A ]
        tags: [ odd_network, even_network ]
      nodes:
        clab-evpnlab-leaf2:
          id: 2
          mgmt_ip: "{{ansible_host}}/24"
          # Uplink switches interfaces (list), interface located on uplink switch. 
          uplink_switch_interfaces: [Ethernet2,Ethernet2]
          vtep_ip: 192.168.254.31
          router_id: 192.168.255.31



node_type_keys:
  spine:
    type: spine
    default_evpn_role: server
    ip_addressing:
      router_id: templates/router_id.j2
  l3leaf:
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    ip_addressing:
      router_id: templates/router_id.j2
      vtep_ip: templates/vtep_ip.j2


